version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/alif
    env_file:
      - ./extra/example-alif-conf.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alif
      - POSTGRES_PASSWORD=alif
      - POSTGRES_DB=alif
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alif"]
      interval: 5s
      timeout: 4s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  redis:
    image: redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 4s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
  chromadb:
    image: chromadb/chroma:0.5.16
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
